version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rksp-postgres
    environment:
      POSTGRES_DB: rksp_db
      POSTGRES_USER: rksp_user
      POSTGRES_PASSWORD: rksp_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
